apiVersion: v1
kind: Service
metadata:
  name: siyuan
  labels:
    app: siyuan
spec:
  type: LoadBalancer
  ports:
  - name: "siyuan"
    nodePort: 6809
    port: 6809
    targetPort: 6809
  selector:
    app: siyuan
status:
  loadBalancer: {}
