apiVersion: v1
kind: Service
metadata:
  name: siyuan
  labels:
    app: siyuan
spec:
  type: LoadBalancer
  ports:
  - name: "siyuan"
    nodePort: 30001
    port: 30001
    targetPort: 30001
  selector:
    app: siyuan
status:
  loadBalancer: {}
