apiVersion: apps/v1
kind: Deployment
metadata:
  name: siyuan
  labels:
    app: siyuan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: siyuan
  template:
    metadata:
      labels:
        app: siyuan
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 985
        fsGroup: 985
      containers:
      - name: siyuan
        image: docker.io/b3log/siyuan:latest
        command: ["/opt/siyuan/kernel"]
        args: ["--workspace", "/home/ssfdust/Documents/SiYuan"]
        volumeMounts:
        - name: workspace
          mountPath: /home/ssfdust/Documents/SiYuan
      - name: caddy
        image: docker.io/ssfdust/siyuan-pod:042803
      volumes:
      - name: workspace
        hostPath:
          path: /home/ssfdust/Documents/SiYuan
